package main

var validationStatus = "validationStatus"
var transformationStatus = "transformationStatus"
var storeStatus = "storeStatus"
var nycYellowTaxis = "nycYellowTaxis"
var storeRequestUuid = "StoreRequestUUID"
var validate = "validate"
var transform = "transform"
var store = "store"
var authorizerS = "authorizer"
var flagValidateFailed = "flagValidateFailed"
var flagTransformFailed = "flagTransformFailed"
var flagStoreFailed = "flagStoreFailed"
var lambdaTimeout int32 = 10
var criticalDataPipeline = "CriticalDataPipeline"
var pipeline = "pipeline"
var criticalDataPipelineIntegration = "CriticalDataPipeline integration"
var postSlashStore = "POST /store"
var bootstrap = "bootstrap"
var twoDotZero = "2.0"
var oneDotZero = "1.0"
var startExecution = "StepFunctions-StartExecution"
var s1000 = "1000"
var dataPipelineAuthSecret = "DataPipelineAuthKey"
var secretDescription = "secret for data pipeline HTTP methods"
var dataPipelineAuthorizer = "DataPipelineAuthorizer"
var zeroVal int32 = 0
var trueVal = true
