package main

var validationStatus = "validationStatus"
var transformationStatus = "transformationStatus"
var storeStatus = "storeStatus"
var nycYellowTaxis = "nycYellowTaxis"
var idx = "Idx"
var validate = "validate"
var transform = "transform"
var store = "store"
var flagValidateFailed = "flagValidateFailed"
var flagTransformFailed = "flagTransformFailed"
var flagStoreFailed = "flagStoreFailed"
var lambdaTimeout int32 = 10
var criticalDataPipeline = "CriticalDataPipeline"
var pipeline = "pipeline"
var criticalDataPipelineIntegration = "CriticalDataPipeline integration"
var postSlashStore = "POST /store"
var bootstrap = "bootstrap"
var oneDotZero = "1.0"
var startExecution = "StepFunctions-StartExecution"
