package main

var validationStatus = "validationStatus"
var transformationStatus = "transformationStatus"
var storeStatus = "storeStatus"
var nycYellowTaxis = "nycYellowTaxis"

var idx = "Idx"
var nextIdx = "NextIdx"
var origData = "OrigData"
var status = "Status"
var reason = "Reason"

var vendor = "Vendor"
var pickupTime = "PickupTime"
var dropoffTime = "DropoffTime"
var passengerCount = "PassengerCount"
var tripDistance = "TripDistance"
var ratecode = "Ratecode"
var storeAndFwdFlag = "StoreAndFwdFlag"
var puLocationId = "PuLocationId"
var doLocationId = "DoLocationId"
var paymentType = "PaymentType"
var fareAmount = "FareAmount"
var extra = "Extra"
var mtaTax = "MtaTax"
var tipAmount = "TipAmount"
var tollsAmount = "TollsAmount"
var improvementSurcharge = "ImprovementSurcharge"
var totalAmount = "TotalAmount"
var congestionSurcharge = "CongestionSurcharge"
var airportFee = "AirportFee"
