name: Go

on: [push]

jobs:
  build:
    name: Check build on golang version ${{ matrix.go-version }} with ${{ matrix.os }} as OS
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: [ '1.21.x' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version
      - name: Build deployment program
        run: cd deploy && bash build.nix.sh && cd ..
      - name: Build injector
        run: cd inject_data && bash build.nix.sh && cd ..
      - name: Build lambdas
        run: cd lambdas && bash build-pkg.nix.sh && cd ..
